logs:
    image: "radial/axle-base:latest"
    volumes:
        - /log
hub:
    image: "radial/hub-base:latest"
    volumes_from:
        - logs
    volumes:
        - /config
        - /data
        - /run
owncloud:
  image: "radial/owncloud:latest"
    volumes_from:
        - hub
